---
title: "Final Project--Oil and Civil War"
author: "Mason Rodriguez"
description: "Oil and Politics"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring the relationship between oil and politics. If I can find Mexico specific data, then I would like to focus on different states in Mexico, specifically how the presence of the state owned oil company, PEMEX might effect party voting. If this data does not exist, then I could look more broadly at how oil wealth is related to civil wars or similar conflicts within different countries.

## Proposal

Does the presence of oil wealth increase the chance of civil war in any given country? In this study, I will examine whether or not countries whose oil exports make up a significant portion of GDP are more inclined toward civil war than those with economies less dependent on oil. I hypothesize that oil wealth decreases the incidence of civil war. I expect countries with oil wealth to be more authoritarian and have stronger state capacity. I would expect the governments of these countries to clamp down on dissent before the point of civil war and thus be fairly insulated from it. The basic unit of analysis will be a country and I will be using Civil Wars dataset posted on the GOV50 website. The explanatory variable is whether or not the country has a significant amount of oil, defined in my data as a country with 1/3 of export revenues coming from oil. This is coded as 1 if true and 0 if not. My outcome variable is whether or not there was a civil war in that country, 1 if so and 0 if not. This outcome variable is currently given by year, but I will likely merge years into decades or similar larger unit of measurement. If I observe less incidence of civil war in countries with significant oil then my hypothesis will be proven correct. If I observe more civil wars in countries with oil than those without, or no difference between them, then my hypothesis will be proven incorrect. 

## Visualization 1


```{r echo = FALSE}
library(tidyverse)
civilwar <- read_csv("civilwar.csv")


civilwar <- civilwar |>
  mutate(decade = case_when(
    year <= 1949 ~ "1940s",
    year > 1949 & year <= 1959 ~ "1950s",
    year > 1959 & year <= 1969 ~ "1960s",
    year > 1969 & year <= 1979 ~ "1970s",
    year > 1979 & year <= 1989 ~ "1980s",
    year > 1989 & year <= 1999 ~ "1990s"))

civilwar <- civilwar |>
  mutate(region = case_when(
    western == TRUE ~ "Western",
    eeurop == TRUE ~ "Eastern Europe",
    lamerica == TRUE ~ "Latin America",
    ssafrica == TRUE ~ "Sub-Saharan Africa",
    asia == TRUE ~ "Asia",
    nafrme == TRUE ~ "North Africa and Middle East"
  ))

civilwar_counts <- civilwar |>
  select(c(country, year, war, Oil, fuelexp, decade, region)) |>
  group_by(country) |>
  summarize(years_at_war = sum(war),
            years_with_oil = sum(Oil))


#civilwar_counts

plot <- civilwar_counts |>
  ggplot(mapping = aes(x = years_with_oil, y = years_at_war)) +
  geom_point() +
  labs(title = "Oil and Civil War", x = "Years with Oil (1945-1999)", y = "Years in Civil War (1945-1999)")

plot

#compare number of years with oil to number of years with war, by country

```
